/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkers;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Playing board
 * @author sergeyv
 */
public class CheckersBoard extends javax.swing.JPanel {

    /**
     * Creates new form CheckersBoard
     */
    final int TOTAL_SQUARES = 64;
    boolean newGame = true;
    static final Set<Integer> newGameBlueSet = new HashSet<Integer>(Arrays.asList(new Integer[]{1,3,5,7,8,10,12,14,17,19,21,23}));
    static final Set<Integer> newGameRedSet = new HashSet<Integer>(Arrays.asList(new Integer[]{40,42,44,46,49,51,53,55,56,58,60,62}));

    /**
     * Holds a list of all pawns currently on the board
     */
    public ArrayList<Pawn> pawns; 

    /**
     * Holds a list of all board squares
     */
    public ArrayList<Square> squares; 
    
    /**
     * 
     */
    public CheckersBoard() {
        initComponents();
        squares = new ArrayList<>();
        pawns = new ArrayList<Pawn>();
        DragListener drag = new DragListener();
        this.addMouseListener( drag );
        this.addMouseMotionListener( drag );
        newGame = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(360, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void paintComponent(Graphics graphics) {
        Graphics2D g = (Graphics2D) graphics;
        super.paintComponent(g);
        for (int i = 0; i < TOTAL_SQUARES; i++){
            Square s = new Square(i);
            if (newGame){
                if (newGameBlueSet.contains(i)){
                    Color color = Color.BLUE;
                    Pawn p = new Pawn(s, color);
                    pawns.add(p);
                    s.setPawn(p);
                } else if(newGameRedSet.contains(i)){
                    Color color = Color.RED;
                    Pawn p = new Pawn(s, color);
                    pawns.add(p);
                    s.setPawn(p);         
                }
            }
            s.paintComponent(g);
            squares.add(s);
        }
        for (Pawn p:pawns){
            p.paint(g);
        }
        newGame = false;
    
    }

  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

